// Sign-up copy (copy-baseline §6 + ux-research §4.4 sign-up 1–2). NL je-form, FR vous-form.
import facts from '@shared/content/facts.json';
import type { Locale } from '../lib/estimate';

const NNBSP = ' ';
export function signupCopy(locale: Locale) {
  const fr = locale === 'fr-be';
  const k = fr ? 'fr' : 'nl';
  const plan = (s: string) => facts.plans.find(p => p.slug === s)!;
  const plans = ['switch', 'switch-plus', 'premium'].map(s => {
    const p = plan(s);
    return { slug: s, name: p.shortName, yearly: p.priceYearly, monthly: p.priceMonthly, sub: p.priceDisplay[k].sub, tagline: p.valueProposition[k],
      points: s === 'switch' ? [p.features[0][k], p.features[2][k]] : s === 'switch-plus' ? [p.features[1][k], p.features[2][k]] : [p.features[1][k], p.features[3][k]] };
  });
  return fr ? {
    meta: { title: 'Inscription | June', description: 'Commencez votre inscription June en deux minutes. Votre code postal et votre adresse e-mail suffisent pour commencer.' },
    h1: 'Commencez à économiser', sub: 'Deux minutes, sans engagement. Vous ne payez rien pour l’instant.',
    steps: ['Votre logement', 'Compteur et extras', 'Votre estimation', 'Abonnement et e-mail'],
    progress: (n: number) => `Étape ${n} sur 4`, time: 'environ 2 minutes', docTitle: (n: number, label: string) => `Étape ${n} sur 4 · ${label} – Inscription | June`,
    chosen: 'Abonnement choisi :', change: 'Modifier', prefilled: 'Repris de votre calcul :',
    errTitle: 'Vérifiez ces champs :',
    s1: { h: 'Où habitez-vous ?', pc: 'Code postal', pcHelp: 'Pour savoir quel gestionnaire de réseau et quelles offres s’appliquent chez vous.', pcEmpty: 'Indiquez votre code postal.', pcInvalid: 'Un code postal belge compte 4 chiffres.',
      energy: 'Que voulez-vous faire comparer ?', energyOpts: { elec: 'Électricité', both: 'Électricité et gaz' },
      housing: 'Type de logement', housingHelp: 'Pour estimer votre consommation si vous ne la connaissez pas.', housingOpts: { apartment: 'Appartement', terraced: 'Mitoyenne', semi: '3 façades', detached: '4 façades' },
      know: 'Vous connaissez votre consommation annuelle ? (facultatif)', knowHelp: 'Vous la trouvez sur votre facture de régularisation. Sinon, nous l’estimons provisoirement sur la base de votre logement.',
      elec: 'Électricité', gas: 'Gaz', unit: 'kWh par an', tooMuch: 'Cela nous semble beaucoup. Pouvez-vous vérifier ?', choose: 'Faites un choix.',
      regions: { vl: 'Flandre', wa: 'Wallonie', bxl: 'Bruxelles' } },
    s2: { h: 'Votre compteur et vos extras', meter: 'Quel compteur avez-vous ?', meterOpts: { digital: 'Compteur numérique', analogue: 'Compteur analogique', unknown: 'Je ne sais pas' },
      meterHelp: 'Un compteur numérique a un petit écran et des boutons, et généralement un port P1.',
      solar: 'Avez-vous des panneaux solaires ?', yes: 'Oui', no: 'Non',
      extras: 'Autres équipements (facultatif)', extrasOpts: { ev: 'Voiture électrique', heatpump: 'Pompe à chaleur' }, extrasHelp: 'Cela nous aide à comparer les bons contrats plus tard. Cela ne change pas l’estimation.',
      budget: 'Compteur à budget ou tarif social ?', budgetB: 'Le tarif social s’applique chez tous les fournisseurs. Avec un compteur à budget, June ne peut pas encore vous aider pour l’instant. Posez-nous la question, nous vous expliquons vos options.',
      budgetFlag: 'règle exacte à confirmer par June', choose: 'Faites un choix.' },
    s3: { h: 'Votre estimation indicative', label: 'Économie estimée', chip: 'Indicatif · illustratif', per: (p: string) => `par an, après l’abonnement ${p}`,
      elec: 'Électricité', gas: 'Gaz', fee: (p: string) => `Abonnement ${p}`,
      rec: 'Recommandé pour vous', recWhy: { 'switch-plus': 'Résultat garanti, avec n’importe quel compteur.', premium: 'Compteur numérique et panneaux solaires : le June Dongle vous montre votre production en direct.' },
      lowT: 'Vous êtes déjà bien placé.', lowB: 'June veille à ce que ça dure. Nous comparons chaque mois, et avec la garantie de gain, vous récupérez 99 € si vous n’économisez pas plus que votre abonnement.',
      after: 'Votre économie réelle, nous la calculons après l’inscription, avec vos propres données de consommation.', method: 'Comment calculons-nous ?',
      methodTitle: 'Notre calcul, en clair', methodItems: [
        'Consommation : une moyenne pour votre type de logement, ou vos propres chiffres.',
        'Écart de prix : entre un contrat jamais changé et le contrat le plus avantageux parmi ceux que nous comparons (0,03 à 0,06 € par kWh d’électricité, 0,008 à 0,016 € par kWh de gaz), d’où une fourchette.',
        'Panneaux solaires : 30 % de prélèvement en moins, plus un écart sur la rémunération de l’injection.',
        'Moins votre abonnement, déjà déduit.',
      ], methodNote: 'Modèle illustratif calculé dans votre navigateur, pas encore validé par June. Ce n’est pas une offre.',
      cta: (p: string) => `Continuer avec ${p}`, other: 'Choisir un autre abonnement', noscript: 'Votre estimation s’affiche ici quand JavaScript est activé. Sinon, nous la calculons après votre inscription.' },
    s4: { h: 'Votre abonnement et votre e-mail', plan: 'Votre abonnement', recBadge: 'Recommandé', perYear: 'par an', monthly: (m: string) => `${m} par mois, facturé annuellement`,
      premiumAnalogue: 'Premium fonctionne uniquement avec un compteur numérique. Choisissez Switch ou Switch Plus, ou continuez si vous recevez bientôt un compteur numérique.',
      pref: 'Quand June trouve un contrat plus avantageux…', prefOpts: { auto: ['Changez automatiquement', 'Vous êtes informé de chaque changement.'], ask: ['Demandez-moi d’abord', 'Vous validez chaque changement.'] },
      green: 'Je veux uniquement de l’électricité 100 % verte', greenHelp: 'Nous ne comparons alors que des contrats 100 % verts selon le fournisseur.',
      name: 'Prénom (facultatif)', email: 'Adresse e-mail', emailHelp: 'Nous l’utilisons uniquement pour votre inscription et votre compte, et pour vous envoyer votre estimation.',
      emailEmpty: 'Indiquez votre adresse e-mail.', emailInvalid: 'Cette adresse e-mail ne semble pas correcte.', required: 'obligatoire',
      terms: 'J’accepte les conditions générales et j’ai lu la déclaration de confidentialité.', termsFlag: 'liens à venir', termsErr: 'Acceptez les conditions pour continuer.',
      marketing: 'Envoyez-moi de temps en temps des conseils et des nouvelles de June.', marketingHelp: 'Facultatif. Vous pouvez vous désinscrire à tout moment.',
      referral: 'Vous avez un code de parrainage ou de partenaire ?', referralL: 'Code',
      submit: 'Démarrer mon inscription', under: 'Vous ne payez rien pour l’instant. Vous disposez de 14 jours de rétractation après la souscription de votre abonnement.',
      next: 'Ensuite : votre adresse, votre code EAN et votre fournisseur actuel. Gardez votre facture à portée de main.' },
    done: { h: 'Consultez votre boîte mail', body: (e: string) => `Nous avons envoyé un e-mail à ${e}. Cliquez sur le lien pour finaliser votre inscription.`, bodyNoEmail: 'Nous vous avons envoyé un e-mail. Cliquez sur le lien pour finaliser votre inscription.',
      summary: 'Votre résumé', plan: 'Abonnement', pref: 'Préférence', where: 'Code postal', est: 'Estimation indicative',
      next: 'Et ensuite ?', nextItems: ['Confirmez votre adresse e-mail.', 'Encodez votre adresse, votre code EAN et votre fournisseur actuel.', 'June compare le marché et vous tient informé.'],
      notReceived: 'Rien reçu ? Vérifiez vos spams ou', resend: 'renvoyez l’e-mail', resent: 'C’est renvoyé. Vérifiez aussi vos spams.', home: 'Retour à l’accueil',
      proto: 'Prototype : aucune donnée n’est envoyée.' },
    back: 'Précédent', next: 'Suivant', toEstimate: 'Voir mon estimation', edit: 'Modifier',
    asideH: 'Pourquoi June', aside: [`Plus de 20${NNBSP}000 clients`, '4,3/5 sur Google · plus de 1 200 avis', 'Aucune interruption de votre énergie', 'June n’est pas un fournisseur'],
    needH: 'Pour la suite, gardez à portée de main', need: ['Votre dernière facture (code EAN)', 'Le nom de votre fournisseur actuel'], privacy: 'Nous ne demandons ni adresse, ni EAN, ni IBAN avant votre estimation.',
    plans, guarantee: facts.guarantees.winstgarantie.name.fr,
  } : {
    meta: { title: 'Aanmelden | June', description: 'Meld je aan bij June in twee minuten. Je postcode en je e-mailadres volstaan om te starten.' },
    h1: 'Start met besparen', sub: 'Twee minuten, vrijblijvend. Je betaalt nog niets.',
    steps: ['Je woning', 'Meter en extra’s', 'Jouw schatting', 'Abonnement en e-mail'],
    progress: (n: number) => `Stap ${n} van 4`, time: 'ongeveer 2 minuten', docTitle: (n: number, label: string) => `Stap ${n} van 4 · ${label} – Aanmelden | June`,
    chosen: 'Gekozen abonnement:', change: 'Wijzigen', prefilled: 'Uit je berekening:',
    errTitle: 'Kijk deze velden even na:',
    s1: { h: 'Waar woon je?', pc: 'Postcode', pcHelp: 'Zo weten we welke netbeheerder en welke aanbiedingen er bij jou gelden.', pcEmpty: 'Vul je postcode in.', pcInvalid: 'Een Belgische postcode heeft 4 cijfers.',
      energy: 'Wat wil je laten vergelijken?', energyOpts: { elec: 'Elektriciteit', both: 'Elektriciteit en gas' },
      housing: 'Type woning', housingHelp: 'Om je verbruik te schatten als je het niet kent.', housingOpts: { apartment: 'Appartement', terraced: 'Rijwoning', semi: 'Halfopen', detached: 'Open bebouwing' },
      know: 'Ken je je jaarverbruik? (optioneel)', knowHelp: 'Je vindt het op je jaarlijkse afrekening. Weet je het niet, dan schatten we het voorlopig op basis van je woning.',
      elec: 'Elektriciteit', gas: 'Gas', unit: 'kWh per jaar', tooMuch: 'Dat lijkt ons veel. Kijk je het even na?', choose: 'Maak een keuze.',
      regions: { vl: 'Vlaanderen', wa: 'Wallonië', bxl: 'Brussel' } },
    s2: { h: 'Je meter en je extra’s', meter: 'Welke meter heb je?', meterOpts: { digital: 'Digitale meter', analogue: 'Analoge meter', unknown: 'Ik weet het niet' },
      meterHelp: 'Een digitale meter heeft een schermpje en knoppen, en meestal een P1-poort.',
      solar: 'Heb je zonnepanelen?', yes: 'Ja', no: 'Nee',
      extras: 'Nog andere toestellen? (optioneel)', extrasOpts: { ev: 'Elektrische auto', heatpump: 'Warmtepomp' }, extrasHelp: 'Zo vergelijken we later de juiste contracten. Je schatting verandert er niet door.',
      budget: 'Budgetmeter of sociaal tarief?', budgetB: 'Het sociaal tarief geldt bij elke leverancier. Met een budgetmeter kan June je voorlopig nog niet helpen. Stel ons gerust je vraag, dan leggen we je opties uit.',
      budgetFlag: 'exacte regel te bevestigen door June', choose: 'Maak een keuze.' },
    s3: { h: 'Jouw indicatieve schatting', label: 'Geschatte besparing', chip: 'Indicatief · illustratief', per: (p: string) => `per jaar, na je abonnement ${p}`,
      elec: 'Elektriciteit', gas: 'Gas', fee: (p: string) => `Abonnement ${p}`,
      rec: 'Aanbevolen voor jou', recWhy: { 'switch-plus': 'Gegarandeerd resultaat, met elke meter.', premium: 'Digitale meter en zonnepanelen: met de June Dongle zie je je productie live.' },
      lowT: 'Je zit al goed.', lowB: 'June houdt het zo. We blijven elke maand vergelijken, en met de Winstgarantie krijg je € 99 terug als je niet meer bespaart dan je abonnement.',
      after: 'Je echte besparing berekenen we na je aanmelding, met je eigen verbruiksgegevens.', method: 'Hoe berekenen we dit?',
      methodTitle: 'Zo rekenen we', methodItems: [
        'Verbruik: een gemiddelde voor je type woning, of je eigen cijfers.',
        'Prijsverschil: tussen een contract waar je nooit van wisselde en het voordeligste contract uit onze vergelijking (€ 0,03 tot 0,06 per kWh stroom, € 0,008 tot 0,016 per kWh gas), daarom een bereik.',
        'Zonnepanelen: 30% minder afname, plus een verschil in injectievergoeding.',
        'Min je abonnement, dat is er al af.',
      ], methodNote: 'Illustratief model, berekend in je browser en nog niet gevalideerd door June. Dit is geen aanbod.',
      cta: (p: string) => `Verder met ${p}`, other: 'Ander abonnement kiezen', noscript: 'Je schatting verschijnt hier als JavaScript aan staat. Anders berekenen we ze na je aanmelding.' },
    s4: { h: 'Je abonnement en je e-mailadres', plan: 'Je abonnement', recBadge: 'Aanbevolen', perYear: 'per jaar', monthly: (m: string) => `${m} per maand, jaarlijks gefactureerd`,
      premiumAnalogue: 'Premium werkt enkel met een digitale meter. Kies Switch of Switch Plus, of ga toch verder als je binnenkort een digitale meter krijgt.',
      pref: 'Als June een voordeliger contract vindt…', prefOpts: { auto: ['Wissel automatisch', 'Je krijgt bericht van elke overstap.'], ask: ['Vraag het me eerst', 'Je keurt elke overstap zelf goed.'] },
      green: 'Ik wil alleen 100% groene stroom', greenHelp: 'Dan vergelijken we enkel contracten met 100% groene stroom volgens de leverancier.',
      name: 'Voornaam (optioneel)', email: 'E-mailadres', emailHelp: 'We gebruiken het alleen voor je aanmelding en je account, en om je schatting te bewaren.',
      emailEmpty: 'Vul je e-mailadres in.', emailInvalid: 'Dit e-mailadres lijkt niet te kloppen.', required: 'verplicht',
      terms: 'Ik ga akkoord met de algemene voorwaarden en heb de privacyverklaring gelezen.', termsFlag: 'links volgen', termsErr: 'Ga akkoord met de voorwaarden om verder te gaan.',
      marketing: 'Stuur me af en toe tips en nieuws van June.', marketingHelp: 'Optioneel. Je kan je altijd uitschrijven.',
      referral: 'Heb je een doorverwijs- of partnercode?', referralL: 'Code',
      submit: 'Aanmelding starten', under: 'Je betaalt nog niets. Je hebt 14 dagen bedenktijd nadat je je abonnement afsluit.',
      next: 'Daarna: je adres, je EAN-code en je huidige leverancier. Hou je afrekening bij de hand.' },
    done: { h: 'Check je mailbox', body: (e: string) => `We stuurden een e-mail naar ${e}. Klik op de link om je aanmelding af te ronden.`, bodyNoEmail: 'We stuurden je een e-mail. Klik op de link om je aanmelding af te ronden.',
      summary: 'Je overzicht', plan: 'Abonnement', pref: 'Voorkeur', where: 'Postcode', est: 'Indicatieve schatting',
      next: 'Wat nu?', nextItems: ['Bevestig je e-mailadres.', 'Vul je adres, je EAN-code en je huidige leverancier in.', 'June vergelijkt de markt en houdt je op de hoogte.'],
      notReceived: 'Niets ontvangen? Kijk in je spam of', resend: 'stuur opnieuw', resent: 'Opnieuw verstuurd. Kijk ook in je spam.', home: 'Terug naar de homepagina',
      proto: 'Prototype: er worden geen gegevens verstuurd.' },
    back: 'Vorige', next: 'Volgende', toEstimate: 'Toon mijn schatting', edit: 'Wijzigen',
    asideH: 'Waarom June', aside: ['20.000+ klanten', '4,3/5 op Google · 1.200+ reviews', 'Geen onderbreking van je energie', 'June is geen leverancier'],
    needH: 'Hou straks bij de hand', need: ['Je laatste afrekening (EAN-code)', 'De naam van je huidige leverancier'], privacy: 'We vragen geen adres, EAN of IBAN vóór je schatting.',
    plans, guarantee: facts.guarantees.winstgarantie.name.nl,
  };
}
export type SignupCopy = ReturnType<typeof signupCopy>;
