// Variant A · inner-page copy (NL + FR). Headlines/microcopy are variant copy; every number, price,
// plan feature, guarantee term and FAQ answer is bound from facts.json (via i18n helpers).
import facts from '@shared/content/facts.json';
import { eur, faqById } from './i18n';

const g = facts.guarantees.winstgarantie;
const hiw = facts.howItWorks;

export const pages = {
  'nl-be': {
    crumbsHome: 'Home',
    /* ───────────────────────── Plans ───────────────────────── */
    plans: {
      title: 'Abonnementen en prijzen | June',
      description: `Switch ${eur(69, 'nl-be')}, Switch Plus ${eur(99, 'nl-be')} of Premium ${eur(198, 'nl-be')} per jaar. Vergelijk wat June voor je doet en kies het abonnement dat bij je past.`,
      crumb: 'Abonnementen',
      eyebrow: 'Abonnementen en prijzen',
      h1: 'Een abonnement voor elk huishouden',
      intro: 'Met elk abonnement volgt June de markt voor je op en regelt ze je overstap. Je betaalt één keer per jaar, en je kiest pas na je berekening.',
      facts: ['Eén jaarprijs, jaarlijks gefactureerd', 'Incl. 21% btw', 'Je energie betaal je aan je leverancier'],
      chooser: {
        legend: 'Welke meter heb je?',
        help: 'We tonen welk abonnement het best past. Je kiest altijd zelf.',
        options: [['unknown', 'Weet ik niet'], ['analog', 'Analoog'], ['digital', 'Digitaal'], ['solar', 'Digitaal + zonnepanelen']] as [string, string][],
        fitSolar: 'Past bij je zonnepanelen',
        fitDigital: 'Kan met je digitale meter',
        analogNote: 'Premium vraagt een digitale meter. Switch en Switch Plus werken ook met een analoge meter.',
      },
      tagline: { switch: 'Slim besparen, zonder gedoe.', 'switch-plus': 'Besparen met gegarandeerd resultaat.', premium: 'Volledige controle voor digitale meters.' } as Record<string, string>,
      whoFor: { switch: 'Voor wie gewoon minder wil betalen.', 'switch-plus': 'Voor wie zekerheid wil.', premium: 'Voor wie alles wil zien: verbruik en zonnepanelen.' } as Record<string, string>,
      choose: (n: string) => `Kies ${n}`,
      guaranteeLine: `Winstgarantie bij Switch Plus en Premium: bespaar je in een abonnementsjaar niet meer dan je abonnement kost, dan krijg je ${eur(99, 'nl-be')} terug.`,
      conditions: 'Voorwaarden',
      compare: {
        eyebrow: 'Alles naast elkaar',
        title: 'Wat zit in welk abonnement?',
        caption: 'Vergelijking van de drie June-abonnementen',
        feature: 'Wat je krijgt',
        yes: 'Inbegrepen', no: 'Niet inbegrepen',
        rows: [
          ['Analyse van 17+ leveranciers, minstens elke maand', 1, 1, 1],
          ['Wij regelen de overstap', 1, 1, 1],
          ['Automatisch of na jouw akkoord', 1, 1, 1],
          ['Analoge en digitale meters', 1, 1, 'Enkel digitaal'],
          ['Optie 100% groene energie', 1, 1, 1],
          [`Winstgarantie (${eur(99, 'nl-be')} terug)`, 0, 1, 1],
          ['Jaarlijks besparingsrapport', 0, 1, 1],
          ['June Dongle (P1-poort)', 0, 0, 'Inbegrepen'],
          ['Live verbruik, historiek per kwartier', 0, 0, 1],
          ['Zonnepanelen: zelfverbruik en injectie', 0, 0, 1],
        ] as [string, number | string, number | string, number | string][],
        price: 'Prijs per jaar',
      },
      diy: {
        eyebrow: 'June of zelf vergelijken?',
        title: 'Vergelijken kan je zelf. Blijven vergelijken is het werk.',
        selfTitle: 'Zelf doen',
        self: ['Je zoekt een vergelijker en vult je verbruik in', 'Je kiest, tekent en zegt je oude contract zelf op', 'Volgend jaar begin je opnieuw, als je eraan denkt', 'Gratis, maar het kost je tijd'],
        juneTitle: 'Met June',
        june: ['We toetsen je contract minstens elke maand aan 17+ leveranciers', 'Wij regelen de overstap en de administratie', 'We blijven opvolgen, ook na de overstap', 'Vaste jaarprijs, met winstgarantie bij Switch Plus'],
        note: 'Liever zelf vergelijken? Dat kan gratis met de tools van de regulatoren (VREG, CWaPE, Brugel).',
      },
      earn: {
        title: 'Hoe verdient June geld?',
        body: 'June leeft van de abonnementen van haar klanten. We zijn geen leverancier en kiezen het contract op basis van jouw verbruik.',
        link: 'Meer over onze onafhankelijkheid',
      },
      faqTitle: 'Vragen over prijzen',
      faqIds: ['cost', 'guarantee', 'meters', 'exit-fee'],
      final: { title: 'Eerst je besparing, dan je abonnement.', sub: 'Vul je postcode in. Je kiest je abonnement pas als je je schatting gezien hebt.' },
      sticky: { lead: `Switch Plus · ${eur(99, 'nl-be')} per jaar`, label: 'Kies Switch Plus' },
    },
    /* ───────────────────────── Premium (home + plans) ───────────────────────── */
    premium: {
      eyebrow: 'Premium · met de June Dongle',
      title: 'Zie wat je huis verbruikt. June zorgt voor de prijs.',
      intro: 'Wisselen zit in elk abonnement. Met Premium en de June Dongle zie je ook live wat je huis verbruikt en wat je zonnepanelen opleveren.',
      stageAlt: 'De June Dongle met groen bladvormig snoer naast een smartphone met de June-app: verbruiksgrafiek per dag in het Nederlands.',
      tag: 'Echte June-app',
      steps: [
        { t: 'Steek de dongle in je meter', b: facts.dongle.description.nl },
        { t: 'Live verbruik, historiek per kwartier', b: 'In de app zie je per kwartier wanneer je huis het meest verbruikt, en hoe je dag, week of maand verloopt.' },
        { t: 'Zonnepanelen: zelfverbruik en injectie', b: 'Zie hoeveel zonnestroom je zelf gebruikt en hoeveel je op het net zet. Dat profiel is ook de basis van onze vergelijking.' },
      ],
      phoneAlt: 'De June-app op een smartphone: verbruiksscherm met een staafgrafiek per dag.',
      solarAlt: 'Kaart uit de June-app: zonne-energie, afname van het net, injectie en zelfconsumptie in kWh.',
      requirement: facts.dongle.requirements.nl,
      price: `${eur(198, 'nl-be')} per jaar`,
      priceSub: `${eur(16.5, 'nl-be')} per maand, jaarlijks gefactureerd · June Dongle inbegrepen`,
      cta: 'Kies Premium',
      more: 'Vergelijk met Switch Plus',
      included: 'Alles uit Switch Plus, inclusief winstgarantie',
    },
    /* ───────────────────────── Switch Plus ───────────────────────── */
    switchPlus: {
      title: 'Switch Plus: besparen met winstgarantie | June',
      description: `Bespaar je niet meer dan je abonnement kost, dan krijg je ${eur(99, 'nl-be')} terug. Switch Plus: ${eur(8.25, 'nl-be')} per maand, ${eur(99, 'nl-be')} per jaar.`,
      crumb: 'Switch Plus',
      eyebrow: 'June Switch Plus',
      h1: 'Besparen met gegarandeerd resultaat.',
      sub: `Alles uit Switch, plus de zekerheid dat je abonnement zichzelf terugverdient. Doet het dat niet, dan krijg je ${eur(99, 'nl-be')} terug.`,
      priceMain: eur(99, 'nl-be'),
      pricePer: 'per jaar',
      priceSub: `${eur(8.25, 'nl-be')} per maand · jaarlijks gefactureerd · incl. btw`,
      cta: 'Kies Switch Plus',
      secondary: 'Vergelijk met Switch en Premium',
      stepsEyebrow: 'Winstgarantie',
      stepsTitle: 'Zo werkt de winstgarantie',
      steps: [
        { t: 'Je abonnementsjaar start.', b: 'June volgt je contract op en zet je over wanneer het voordeliger kan.' },
        { t: 'Na een jaar maken we de rekening.', b: 'In je besparingsrapport zie je hoeveel je bespaard hebt.' },
        { t: 'Te weinig bespaard? Geld terug.', b: `Bespaar je niet meer dan je abonnement kost, dan krijg je ${eur(99, 'nl-be')} terug.` },
      ],
      termsTitle: 'De voorwaarden in het kort',
      terms: [g.terms.period.nl, g.terms.measurement.nl, g.terms.payout.nl],
      smallPrint: 'De volledige voorwaarden staan in onze algemene voorwaarden.',
      reportEyebrow: 'Inbegrepen',
      reportTitle: 'Je jaarlijks besparingsrapport',
      reportBody: 'Eén helder overzicht per jaar: wat je verbruikt hebt, bij welke leveranciers je zat, en wat dat opbracht. Het is ook de basis van je winstgarantie.',
      reportAlt: 'Kaart uit de June-app: besparingsrapport met het bedrag dat je bespaarde, de overstap van leverancier en tips.',
      reportTag: 'Voorbeeld uit de June-app',
      alsoTitle: 'Ook inbegrepen',
      whichTitle: 'Switch of Switch Plus?',
      whichBody: 'Kies Switch als je gewoon wil besparen. Kies Switch Plus als je zeker wil zijn dat June zichzelf terugbetaalt. Heb je een digitale meter en wil je live inzicht? Bekijk dan Premium.',
      whichRows: [['Prijs per jaar'], ['Winstgarantie'], ['Besparingsrapport'], ['June Dongle en live data']],
      faqIds: ['guarantee', 'approval', 'exit-fee', 'cost'],
      final: { title: 'Start met Switch Plus', sub: 'Vul je postcode in. We tonen eerst je indicatieve besparing, met Switch Plus al voor je aangeduid.' },
      sticky: { lead: `Switch Plus · ${eur(99, 'nl-be')} per jaar`, label: 'Kies Switch Plus' },
    },
    /* ───────────────────────── How it works ───────────────────────── */
    how: {
      title: 'Hoe werkt June? | Automatisch overstappen van energieleverancier',
      description: 'Koppel je meter, June vergelijkt 17+ leveranciers voor jouw verbruik en regelt de overstap: automatisch of na jouw akkoord.',
      crumb: 'Hoe werkt het',
      eyebrow: 'Hoe werkt het',
      h1: 'Hoe zorgt June dat je een voordelig energietarief hebt?',
      intro: 'Energieprijzen veranderen voortdurend. June volgt ze voor je op, zodat jij dat niet hoeft te doen.',
      summaryLabel: 'In twintig seconden',
      summary: 'Je meldt je één keer aan. June legt jouw verbruik minstens elke maand naast de contracten van 17+ leveranciers. Is er een voordeliger contract, dan regelen wij de overstap: automatisch, of na jouw akkoord.',
      whoTitle: 'Wie doet wat?',
      whoIntro: 'June is geen energieleverancier. Bij een overstap verandert alleen wie je energie factureert.',
      who: [
        { t: 'Jij', b: 'Je meldt je aan en kiest: automatisch wisselen of elke overstap zelf goedkeuren.', tag: '' },
        { t: 'June', b: 'Volgt de markt op, kiest het voordeligste contract uit onze vergelijking en regelt de overstap. Levert zelf geen energie.', tag: '' },
        { t: 'Je leverancier', b: 'Levert je stroom en gas en stuurt je de factuur. Die kan bij een overstap veranderen.', tag: 'Kan veranderen' },
        { t: 'Je netbeheerder', b: 'Beheert de kabels, leidingen en je meter, bv. Fluvius, ORES of Sibelga. Die blijft altijd dezelfde.', tag: 'Blijft hetzelfde' },
      ],
      stepsTitle: 'Stap voor stap',
      steps: hiw.detailed.map(s => ({ t: s.title.nl, b: s.body.nl })),
      modeAuto: 'Automatisch wisselen',
      modeAsk: 'Eerst mijn akkoord',
      youTitle: 'Wat jij doet, wat wij doen',
      you: { t: 'Jij', b: 'Je meldt je aan (twee minuten). Je kiest: automatisch wisselen of zelf goedkeuren. Heb je een analoge meter? Dan geef je af en toe je meterstanden in.' },
      june: { t: 'June', b: 'We volgen de markt op, zoeken het voordeligste contract uit onze vergelijking voor jouw verbruik, sluiten het af, zeggen je oude contract op en houden je op de hoogte.' },
      reassure: [
        { t: 'Geen onderbreking.', b: 'Je meter en je netbeheerder blijven dezelfde.' },
        { t: 'Geen opzegvergoeding.', b: 'Als particulier verander je in België vrij van leverancier.' },
        { t: 'Jij houdt de controle.', b: 'Automatisch wisselen of elke overstap zelf goedkeuren: jij kiest.' },
      ],
      metersTitle: 'Welke meter heb je?',
      digital: { t: 'Digitale meter', b: 'We lezen je verbruik automatisch uit. Met de June Dongle (Premium) zie je het zelfs live.' },
      analog: { t: 'Analoge meter', b: 'Geen probleem. Je geeft je meterstanden zelf in, wij doen de rest.' },
      dongleAlt: 'De June Dongle: wit toestel met een groen, bladvormig snoer.',
      region: { t: 'Capaciteitstarief in Vlaanderen', b: 'In Vlaanderen hangt een deel van je nettarief af van je hoogste kwartierpiek. Dat is een nettarief: het verandert niet als je van leverancier wisselt.' },
      dataTitle: 'Wat we met je gegevens doen',
      dataBody: faqById('data').a.nl,
      dataUse: 'Wat we gebruiken',
      dataUseItems: ['Je verbruik (van je meter, de dongle of je meterstanden)', 'Je postcode, voor de nettarieven in je regio', 'Je huidige en nieuwe contract'],
      dataNever: 'Wat we nooit doen',
      dataNeverItems: ['Je gegevens verkopen', 'Je stroom of gas onderbreken', 'Je meter of aansluiting veranderen'],
      faqIds: ['meters', 'approval', 'no-interruption', 'green'],
      final: { title: 'Laat June het werk doen.', sub: 'Vul je postcode in. In een paar vragen weet je wat June voor jou kan doen.' },
      secondary: 'Bekijk de abonnementen',
    },
    /* ───────────────────────── FAQ ───────────────────────── */
    faq: {
      title: 'Veelgestelde vragen | June',
      description: 'Alles over June: wat het kost, hoe de overstap werkt, de winstgarantie, je meter en je gegevens.',
      crumb: 'Veelgestelde vragen',
      eyebrow: 'Hulp',
      h1: 'Veelgestelde vragen',
      intro: 'Kort antwoord op wat mensen ons het vaakst vragen. Staat je vraag er niet bij? Neem contact met ons op.',
      search: 'Zoek in de vragen',
      searchPh: 'bv. meter, opzeggen, garantie',
      noResults: 'Geen vragen gevonden. Probeer een ander woord, of neem contact met ons op.',
      results: (n: number) => `${n} ${n === 1 ? 'vraag' : 'vragen'} gevonden`,
      groupsLabel: 'Onderwerpen',
      groups: [
        { id: 'over-june', t: 'Over June', ids: ['not-a-supplier', 'independence', 'how-so-much', 'which-suppliers'] },
        { id: 'prijs', t: 'Prijs en abonnement', ids: ['cost', 'guarantee'] },
        { id: 'overstap', t: 'De overstap', ids: ['approval', 'exit-fee', 'no-interruption', 'green'] },
        { id: 'meter', t: 'Je meter en je gegevens', ids: ['meters', 'data'] },
      ],
      more: { t: 'Staat je vraag er niet bij?', b: 'Ons team helpt je graag verder, in het Nederlands of het Frans.', mail: 'Mail ons', phone: 'Bel ons', hours: '[telefoonnummer en openingsuren]' },
      charAlt: '',
      final: { title: 'Klaar om te starten?', sub: 'Vul je postcode in en zie in een paar vragen wat June voor jou kan doen.' },
    },
  },

  'fr-be': {
    crumbsHome: 'Accueil',
    plans: {
      title: 'Abonnements et prix | June',
      description: `Switch ${eur(69, 'fr-be')}, Switch Plus ${eur(99, 'fr-be')} ou Premium ${eur(198, 'fr-be')} par an. Comparez ce que June fait pour vous et choisissez l'abonnement qui vous convient.`,
      crumb: 'Abonnements',
      eyebrow: 'Abonnements et prix',
      h1: 'Un abonnement pour chaque ménage',
      intro: "Avec chaque abonnement, June suit le marché pour vous et gère votre changement. Vous payez une fois par an, et vous ne choisissez qu'après le calcul.",
      facts: ['Un prix annuel, facturé une fois par an', 'TVA 21 % comprise', 'Votre énergie est facturée par votre fournisseur'],
      chooser: {
        legend: 'Quel compteur avez-vous ?',
        help: "Nous indiquons l'abonnement le plus adapté. Vous choisissez toujours vous-même.",
        options: [['unknown', 'Je ne sais pas'], ['analog', 'Analogique'], ['digital', 'Numérique'], ['solar', 'Numérique + panneaux solaires']] as [string, string][],
        fitSolar: 'Idéal avec des panneaux solaires',
        fitDigital: 'Possible avec votre compteur numérique',
        analogNote: 'Premium nécessite un compteur numérique. Switch et Switch Plus fonctionnent aussi avec un compteur analogique.',
      },
      tagline: { switch: 'Économisez malin, sans tracas.', 'switch-plus': 'Économisez, avec un résultat garanti.', premium: 'Le contrôle total pour les compteurs numériques.' } as Record<string, string>,
      whoFor: { switch: 'Pour ceux qui veulent simplement payer moins.', 'switch-plus': 'Pour ceux qui veulent une certitude.', premium: 'Pour ceux qui veulent tout voir : consommation et panneaux solaires.' } as Record<string, string>,
      choose: (n: string) => `Choisir ${n}`,
      guaranteeLine: `Garantie de gain avec Switch Plus et Premium : si vous n'économisez pas plus que le prix de votre abonnement sur une année, vous récupérez ${eur(99, 'fr-be')}.`,
      conditions: 'Conditions',
      compare: {
        eyebrow: 'Côte à côte',
        title: 'Que comprend chaque abonnement ?',
        caption: 'Comparaison des trois abonnements June',
        feature: 'Ce que vous recevez',
        yes: 'Inclus', no: 'Non inclus',
        rows: [
          ['Analyse de plus de 17 fournisseurs, au moins chaque mois', 1, 1, 1],
          ['Nous gérons le changement', 1, 1, 1],
          ['Automatiquement ou après votre accord', 1, 1, 1],
          ['Compteurs analogiques et numériques', 1, 1, 'Numérique uniquement'],
          ['Option 100 % énergie verte', 1, 1, 1],
          [`Garantie de gain (${eur(99, 'fr-be')} remboursés)`, 0, 1, 1],
          ["Rapport d'économies annuel", 0, 1, 1],
          ['June Dongle (port P1)', 0, 0, 'Inclus'],
          ["Consommation en direct, historique par quart d'heure", 0, 0, 1],
          ['Panneaux solaires : autoconsommation et injection', 0, 0, 1],
        ] as [string, number | string, number | string, number | string][],
        price: 'Prix par an',
      },
      diy: {
        eyebrow: 'June ou comparer vous-même ?',
        title: "Comparer, vous pouvez le faire. Continuer à comparer, c'est le vrai travail.",
        selfTitle: 'Vous-même',
        self: ['Vous cherchez un comparateur et encodez votre consommation', 'Vous choisissez, signez et résiliez vous-même votre ancien contrat', "L'an prochain, vous recommencez, si vous y pensez", 'Gratuit, mais cela vous prend du temps'],
        juneTitle: 'Avec June',
        june: ['Nous comparons votre contrat au moins chaque mois à plus de 17 fournisseurs', "Nous gérons le changement et l'administration", 'Nous continuons à suivre, même après le changement', 'Prix annuel fixe, avec garantie de gain chez Switch Plus'],
        note: 'Vous préférez comparer vous-même ? Les outils des régulateurs (CWaPE, Brugel, VREG) sont gratuits.',
      },
      earn: {
        title: 'Comment June gagne-t-elle sa vie ?',
        body: 'June vit des abonnements de ses clients. Nous ne sommes pas fournisseur et choisissons le contrat sur la base de votre consommation.',
        link: 'En savoir plus sur notre indépendance',
      },
      faqTitle: 'Questions sur les prix',
      faqIds: ['cost', 'guarantee', 'meters', 'exit-fee'],
      final: { title: "D'abord votre économie, ensuite votre abonnement.", sub: "Indiquez votre code postal. Vous ne choisissez votre abonnement qu'après avoir vu votre estimation." },
      sticky: { lead: `Switch Plus · ${eur(99, 'fr-be')} par an`, label: 'Choisir Switch Plus' },
    },
    premium: {
      eyebrow: 'Premium · avec le June Dongle',
      title: 'Voyez ce que consomme votre maison. June s’occupe du prix.',
      intro: 'Le changement de fournisseur est compris dans chaque abonnement. Avec Premium et le June Dongle, vous voyez aussi en direct ce que consomme votre maison et ce que produisent vos panneaux.',
      stageAlt: "Le June Dongle avec son câble vert en forme de feuille, à côté d'un smartphone affichant l'app June en français : graphique de consommation par jour.",
      tag: 'La vraie app June',
      steps: [
        { t: 'Branchez le dongle sur votre compteur', b: facts.dongle.description.fr },
        { t: "En direct, historique par quart d'heure", b: "Dans l'app, vous voyez par quart d'heure quand votre maison consomme le plus, et comment se passe votre journée, semaine ou mois." },
        { t: 'Panneaux solaires : autoconsommation et injection', b: "Voyez combien d'électricité solaire vous utilisez vous-même et combien vous injectez sur le réseau. Ce profil est aussi la base de notre comparaison." },
      ],
      phoneAlt: "L'app June sur un smartphone, en français : écran Consommation avec un graphique en barres par jour.",
      solarAlt: '',
      requirement: facts.dongle.requirements.fr,
      price: `${eur(198, 'fr-be')} par an`,
      priceSub: `${eur(16.5, 'fr-be')} par mois, facturé annuellement · June Dongle inclus`,
      cta: 'Choisir Premium',
      more: 'Comparer avec Switch Plus',
      included: "Tout ce qu'offre Switch Plus, garantie de gain comprise",
    },
    switchPlus: {
      title: 'Switch Plus : économisez avec garantie de gain | June',
      description: `Si vous n'économisez pas plus que le prix de votre abonnement, vous récupérez ${eur(99, 'fr-be')}. Switch Plus : ${eur(8.25, 'fr-be')} par mois, ${eur(99, 'fr-be')} par an.`,
      crumb: 'Switch Plus',
      eyebrow: 'June Switch Plus',
      h1: 'Économisez, avec un résultat garanti.',
      sub: `Tout ce qu'offre Switch, plus la certitude que votre abonnement se rembourse. Sinon, vous récupérez ${eur(99, 'fr-be')}.`,
      priceMain: eur(99, 'fr-be'),
      pricePer: 'par an',
      priceSub: `${eur(8.25, 'fr-be')} par mois · facturé annuellement · TVA comprise`,
      cta: 'Choisir Switch Plus',
      secondary: 'Comparer avec Switch et Premium',
      stepsEyebrow: 'Garantie de gain',
      stepsTitle: 'Comment fonctionne la garantie de gain',
      steps: [
        { t: "Votre année d'abonnement commence.", b: "June suit votre contrat et vous fait changer quand c'est plus avantageux." },
        { t: 'Après un an, nous faisons le compte.', b: 'Votre rapport d’économies montre combien vous avez économisé.' },
        { t: 'Pas assez économisé ? Remboursé.', b: `Si vous n'économisez pas plus que le prix de votre abonnement, vous récupérez ${eur(99, 'fr-be')}.` },
      ],
      termsTitle: 'Les conditions en bref',
      terms: [g.terms.period.fr, g.terms.measurement.fr, g.terms.payout.fr],
      smallPrint: 'Toutes les conditions figurent dans nos conditions générales.',
      reportEyebrow: 'Inclus',
      reportTitle: "Votre rapport d'économies annuel",
      reportBody: "Un aperçu clair chaque année : ce que vous avez consommé, chez quels fournisseurs vous étiez, et ce que cela vous a rapporté. C'est aussi la base de votre garantie de gain.",
      reportAlt: '',
      reportTag: 'Exemple',
      alsoTitle: 'Également inclus',
      whichTitle: 'Switch ou Switch Plus ?',
      whichBody: 'Choisissez Switch si vous voulez simplement économiser. Choisissez Switch Plus si vous voulez être sûr que June se rembourse. Vous avez un compteur numérique et voulez un suivi en direct ? Découvrez Premium.',
      whichRows: [['Prix par an'], ['Garantie de gain'], ["Rapport d'économies"], ['June Dongle et données en direct']],
      faqIds: ['guarantee', 'approval', 'exit-fee', 'cost'],
      final: { title: 'Commencer avec Switch Plus', sub: 'Indiquez votre code postal. Nous vous montrons d’abord votre économie indicative, avec Switch Plus déjà sélectionné.' },
      sticky: { lead: `Switch Plus · ${eur(99, 'fr-be')} par an`, label: 'Choisir Switch Plus' },
    },
    how: {
      title: 'Comment fonctionne June ? | Changer de fournisseur automatiquement',
      description: 'Connectez votre compteur, June compare plus de 17 fournisseurs pour votre consommation et gère le changement : automatiquement ou après votre accord.',
      crumb: 'Comment ça marche',
      eyebrow: 'Comment ça marche',
      h1: "Comment June veille-t-elle à ce que vous ayez un tarif d'énergie avantageux ?",
      intro: "Les prix de l'énergie changent sans cesse. June les suit pour vous, pour que vous n'ayez pas à le faire.",
      summaryLabel: 'En vingt secondes',
      summary: "Vous vous inscrivez une seule fois. Au moins une fois par mois, June compare votre consommation aux contrats de plus de 17 fournisseurs. S'il existe un contrat plus avantageux, nous gérons le changement : automatiquement, ou après votre accord.",
      whoTitle: 'Qui fait quoi ?',
      whoIntro: "June n'est pas un fournisseur d'énergie. Lors d'un changement, seul celui qui vous facture l'énergie change.",
      who: [
        { t: 'Vous', b: 'Vous vous inscrivez et choisissez : changement automatique ou validation de chaque changement.', tag: '' },
        { t: 'June', b: "Suit le marché, choisit le contrat le plus avantageux parmi ceux que nous comparons et gère le changement. Ne fournit pas d'énergie.", tag: '' },
        { t: 'Votre fournisseur', b: "Vous livre l'électricité et le gaz et vous envoie la facture. Il peut changer.", tag: 'Peut changer' },
        { t: 'Votre gestionnaire de réseau', b: 'Gère les câbles, les conduites et votre compteur, par ex. ORES, Sibelga, RESA ou Fluvius. Il reste toujours le même.', tag: 'Reste le même' },
      ],
      stepsTitle: 'Étape par étape',
      steps: hiw.detailed.map(s => ({ t: s.title.fr, b: s.body.fr })),
      modeAuto: 'Changement automatique',
      modeAsk: "D'abord mon accord",
      youTitle: 'Ce que vous faites, ce que nous faisons',
      you: { t: 'Vous', b: 'Vous vous inscrivez (deux minutes). Vous choisissez : changement automatique ou validation par vous. Vous avez un compteur analogique ? Vous encodez vos index de temps en temps.' },
      june: { t: 'June', b: 'Nous suivons le marché, cherchons parmi les contrats comparés le plus avantageux pour votre consommation, le souscrivons, résilions votre ancien contrat et vous tenons informé.' },
      reassure: [
        { t: 'Aucune interruption.', b: 'Votre compteur et votre gestionnaire de réseau restent les mêmes.' },
        { t: "Pas d'indemnité de rupture.", b: 'En Belgique, un particulier change librement de fournisseur.' },
        { t: 'Vous gardez le contrôle.', b: "Changement automatique ou validation de chaque changement : c'est vous qui choisissez." },
      ],
      metersTitle: 'Quel compteur avez-vous ?',
      digital: { t: 'Compteur numérique', b: 'Nous relevons votre consommation automatiquement. Avec le June Dongle (Premium), vous la voyez même en direct.' },
      analog: { t: 'Compteur analogique', b: 'Pas de problème. Vous encodez vos index, nous faisons le reste.' },
      dongleAlt: 'Le June Dongle : boîtier blanc avec un câble vert en forme de feuille.',
      region: { t: 'Tarif capacitaire : uniquement en Flandre', b: "Le tarif capacitaire ne s'applique qu'en Flandre. En Wallonie et à Bruxelles, il ne vous concerne pas. Dans tous les cas, il fait partie des frais de réseau et ne change pas quand vous changez de fournisseur." },
      dataTitle: 'Ce que nous faisons de vos données',
      dataBody: faqById('data').a.fr,
      dataUse: 'Ce que nous utilisons',
      dataUseItems: ['Votre consommation (compteur, dongle ou vos index)', 'Votre code postal, pour les frais de réseau de votre région', 'Votre contrat actuel et le nouveau'],
      dataNever: 'Ce que nous ne faisons jamais',
      dataNeverItems: ['Vendre vos données', "Interrompre votre électricité ou votre gaz", 'Changer votre compteur ou votre raccordement'],
      faqIds: ['meters', 'approval', 'no-interruption', 'green'],
      final: { title: 'Laissez June faire le travail.', sub: 'Indiquez votre code postal. En quelques questions, vous savez ce que June peut faire pour vous.' },
      secondary: 'Voir les abonnements',
    },
    faq: {
      title: 'Questions fréquentes | June',
      description: 'Tout sur June : le prix, le changement de fournisseur, la garantie de gain, votre compteur et vos données.',
      crumb: 'Questions fréquentes',
      eyebrow: 'Aide',
      h1: 'Questions fréquentes',
      intro: "Des réponses courtes aux questions qu'on nous pose le plus souvent. Votre question n'y figure pas ? Contactez-nous.",
      search: 'Rechercher dans les questions',
      searchPh: 'ex. compteur, résilier, garantie',
      noResults: 'Aucune question trouvée. Essayez un autre mot, ou contactez-nous.',
      results: (n: number) => `${n} question${n === 1 ? '' : 's'} trouvée${n === 1 ? '' : 's'}`,
      groupsLabel: 'Sujets',
      groups: [
        { id: 'a-propos', t: 'À propos de June', ids: ['not-a-supplier', 'independence', 'how-so-much', 'which-suppliers'] },
        { id: 'prix', t: 'Prix et abonnement', ids: ['cost', 'guarantee'] },
        { id: 'changement', t: 'Le changement de fournisseur', ids: ['approval', 'exit-fee', 'no-interruption', 'green'] },
        { id: 'compteur', t: 'Votre compteur et vos données', ids: ['meters', 'data'] },
      ],
      more: { t: "Votre question n'y figure pas ?", b: 'Notre équipe vous aide volontiers, en français ou en néerlandais.', mail: 'Écrivez-nous', phone: 'Appelez-nous', hours: '[numéro de téléphone et horaires]' },
      charAlt: '',
      final: { title: 'Prêt à commencer ?', sub: 'Indiquez votre code postal et découvrez en quelques questions ce que June peut faire pour vous.' },
    },
  },
};
export type Pages = (typeof pages)['nl-be'];
/** FAQ answer shortened to its confirmed part (freeze §3: may shorten, never strengthen). */
export const faqAnswer = (a: string) => a.replace(/\s*\[[^\]]*\]\s*/g, ' ').trim();
