// Sign-up (aanmelden / inscription) copy + client data. Copy follows copy-baseline §6 and ux-research §4.4.
import { eur, thousands } from './i18n';

export const signupCopy = {
  'nl-be': {
    title: 'Aanmelden | June',
    description: 'Meld je aan bij June in twee minuten. Je postcode en je e-mailadres volstaan om te starten.',
    h1: 'Meld je aan in twee minuten',
    help: 'Hulp nodig?',
    back: 'Terug naar june.energy',
    progressLabel: 'Voortgang',
    progress: ['Je woning', 'Je schatting', 'Abonnement en e-mail'],
    stepOf: (n: number) => `Stap ${n} van 3`,
    time: 'ongeveer 2 minuten',
    planChip: 'Gekozen abonnement:',
    planChange: 'Wijzigen kan in stap 3',
    errTitle: 'Nog even nakijken:',
    noscript: 'Je browser voert geen JavaScript uit. Aanmelden kan ook via [e-mail] of [telefoonnummer].',
    s1: {
      title: 'Vertel ons iets over je woning',
      intro: 'Geen persoonsgegevens nodig. Zo tonen we meteen een indicatieve besparing.',
      postcode: 'Postcode',
      postcodeHelp: 'Zo weten we welke netbeheerder en welke aanbiedingen er bij jou gelden.',
      postcodePh: 'bv. 9000',
      energy: 'Wat wil je laten vergelijken?',
      energyOpts: [['both', 'Elektriciteit en gas'], ['elec', 'Enkel elektriciteit']],
      household: 'Met hoeveel personen woon je?',
      householdOpts: [['1', '1 persoon'], ['2', '2 personen'], ['3-4', '3–4 personen'], ['5+', '5 of meer']],
      usageToggle: 'Ik ken mijn jaarverbruik (optioneel)',
      usageHelp: 'Je vindt het op je jaarlijkse afrekening. Weet je het niet, dan schatten we het voorlopig op basis van je gezin.',
      usageElec: 'Elektriciteit (kWh per jaar)',
      usageGas: 'Gas (kWh per jaar)',
      meter: 'Welke meter heb je?',
      meterOpts: [['digital', 'Digitale meter'], ['analog', 'Analoge meter'], ['unknown', 'Weet ik niet']],
      meterHelp: 'Een digitale meter heeft een schermpje en knoppen, en meestal een P1-poort.',
      solar: 'Heb je zonnepanelen?',
      solarOpts: [['yes', 'Ja'], ['no', 'Nee'], ['unknown', 'Weet ik niet']],
      extras: 'Heb je ook… (optioneel)',
      extrasOpts: [['ev', 'Elektrische wagen'], ['hp', 'Warmtepomp']],
      edge: 'Budgetmeter of sociaal tarief? Neem eerst contact met ons op, dan bekijken we samen wat kan.',
      submit: 'Toon mijn schatting',
      micro: 'Gratis · vrijblijvend · je kiest pas na je schatting',
    },
    est: {
      title: 'Je indicatieve besparing',
      tag: 'Indicatief',
      perYear: 'per jaar',
      for: (hh: string, place: string, energy: string) => `Voor ${hh} in ${place}, ${energy}.`,
      energyWord: { both: 'elektriciteit en gas', elec: 'enkel elektriciteit' } as Record<string, string>,
      hhWord: { '1': '1 persoon', '2': '2 personen', '3-4': 'een gezin van 3–4', '5+': 'een gezin van 5 of meer', usage: 'jouw opgegeven verbruik' } as Record<string, string>,
      after: (plan: string, price: string) => `Na je abonnement (${plan}, ${price} per jaar)`,
      afterNote: 'Wat je naar schatting overhoudt',
      recTitle: 'Aanbevolen voor jou',
      recPlus: 'Switch Plus, met winstgarantie. Bespaar je in een abonnementsjaar niet meer dan je abonnement kost, dan krijg je € 99 terug.',
      recPremium: 'Premium. Je hebt een digitale meter en zonnepanelen: met de June Dongle zie je live je zelfverbruik en je injectie. Winstgarantie inbegrepen.',
      solarNote: 'Met zonnepanelen hangt je besparing ook af van je injectie. Dat nemen we mee in je persoonlijke berekening.',
      method: 'Hoe berekenen we dit?',
      methodBody: 'Een indicatieve vork op basis van gemiddelde besparingen bij huishoudens met een vergelijkbaar profiel [methode, periode en steekproef door June te bevestigen]. Dit is geen offerte en geen belofte. Je persoonlijke besparing berekenen we na je aanmelding, met je echte verbruik en je huidige contract.',
      cta: (plan: string) => `Verder met ${plan}`,
      edit: 'Gegevens aanpassen',
      compare: 'Vergelijk de abonnementen',
    },
    s2: {
      title: 'Kies je abonnement en bewaar je schatting',
      plan: 'Je abonnement',
      recBadge: 'Aanbevolen · met winstgarantie',
      forYou: 'Past bij jouw situatie',
      perYear: 'per jaar',
      perMonth: (m: string) => `${m} per maand, jaarlijks gefactureerd`,
      planLines: { switch: 'Automatisch wisselen, zonder garantie', 'switch-plus': `Met winstgarantie: ${eur(99, 'nl-be')} terug als je niet meer bespaart dan je abonnement kost`, premium: 'Met June Dongle, live data en winstgarantie' } as Record<string, string>,
      premiumAnalog: 'Premium werkt enkel met een digitale meter. Kies Switch of Switch Plus, of ga toch verder als je binnenkort een digitale meter krijgt.',
      mode: 'Hoe wil je wisselen?',
      modeOpts: [['auto', 'Automatisch', 'June wisselt voor je zodra het voordeliger kan. Je krijgt altijd bericht.'], ['ask', 'Vraag het me eerst', 'Je keurt elke overstap zelf goed.']],
      green: 'Ik wil alleen 100% groene stroom',
      greenHelp: 'Dan vergelijken we enkel contracten met 100% groene stroom volgens de leverancier.',
      name: 'Voornaam (optioneel)',
      email: 'E-mailadres',
      emailHelp: 'We sturen je schatting en de link om verder te gaan. We gebruiken het alleen voor je aanmelding en je account.',
      terms: 'Ik ga akkoord met de [algemene voorwaarden] en heb de [privacyverklaring] gelezen.',
      marketing: 'Stuur me af en toe tips en nieuws van June (optioneel).',
      code: 'Heb je een partner- of doorverwijscode?',
      codeLabel: 'Code',
      submit: 'Aanmelding starten',
      micro: 'Je betaalt nog niets. Je hebt 14 dagen bedenktijd nadat je je abonnement afsluit.',
      next: 'Daarna: je adres, EAN-code en huidige leverancier. Hou je afrekening bij de hand.',
      prev: 'Vorige',
    },
    done: {
      title: 'Check je mailbox',
      body: (e: string) => `We stuurden een e-mail naar ${e}. Klik op de link om je aanmelding af te ronden.`,
      summary: 'Je keuzes',
      nextTitle: 'Wat gebeurt er nu?',
      next: ['Je rondt je aanmelding af via de link: adres, EAN-code, huidige leverancier.', 'We berekenen je persoonlijke besparing met je echte verbruik.', 'Daarna volgt June de markt voor je op, elke maand opnieuw.'],
      resend: 'Niets ontvangen? Kijk in je spam of stuur opnieuw.',
      home: 'Terug naar de startpagina',
      demo: 'Prototype: er is niets verstuurd.',
    },
    err: {
      pcEmpty: 'Vul je postcode in.',
      pcBad: 'Een Belgische postcode heeft 4 cijfers, bv. 9000.',
      choice: 'Maak een keuze.',
      household: 'Kies het aantal personen, of vul je jaarverbruik in.',
      usage: 'Dat lijkt ons veel. Kijk je het even na?',
      email: 'Dit e-mailadres lijkt niet te kloppen.',
      emailEmpty: 'Vul je e-mailadres in.',
      terms: 'Ga akkoord met de voorwaarden om verder te gaan.',
    },
    town: (pc: string, town: string, region: string, dso: string) => `${pc} ${town} · ${region} · netbeheerder ${dso}`,
    regionOnly: (pc: string, prov: string, region: string, dso: string) => `${pc} · ${prov}, ${region} · netbeheerder ${dso}`,
    regionVL: 'In Vlaanderen telt ook je hoogste kwartierpiek mee in je nettarief (capaciteitstarief). Dat verandert niet als je van leverancier wisselt.',
    aside: {
      title: 'Waarom 20.000+ gezinnen June kozen',
      items: ['June is geen leverancier: wij werken voor jou', 'Je stroom blijft gewoon komen, zelfde meter', 'Geen verbrekingsvergoeding bij je huidige leverancier', `Winstgarantie bij Switch Plus: ${eur(99, 'nl-be')} terug als je niet meer bespaart dan je abonnement kost`],
      privacy: 'Je gegevens blijven bij June. We verkopen ze niet.',
    },
    customers: `${thousands(20000, 'nl-be')}+ klanten`,
  },
  'fr-be': {
    title: 'Inscription | June',
    description: 'Inscrivez-vous chez June en deux minutes. Votre code postal et votre adresse e-mail suffisent pour commencer.',
    h1: 'Inscrivez-vous en deux minutes',
    help: "Besoin d'aide ?",
    back: 'Retour à june.energy',
    progressLabel: 'Progression',
    progress: ['Votre logement', 'Votre estimation', 'Abonnement et e-mail'],
    stepOf: (n: number) => `Étape ${n} sur 3`,
    time: 'environ 2 minutes',
    planChip: 'Abonnement choisi :',
    planChange: "Modifiable à l'étape 3",
    errTitle: 'Encore un petit contrôle :',
    noscript: "Votre navigateur n'exécute pas JavaScript. Vous pouvez aussi vous inscrire via [e-mail] ou [numéro de téléphone].",
    s1: {
      title: 'Parlez-nous de votre logement',
      intro: 'Aucune donnée personnelle nécessaire. Nous vous montrons tout de suite une économie indicative.',
      postcode: 'Code postal',
      postcodeHelp: "Pour savoir quel gestionnaire de réseau et quelles offres s'appliquent chez vous.",
      postcodePh: 'ex. 1000',
      energy: 'Que voulez-vous faire comparer ?',
      energyOpts: [['both', 'Électricité et gaz'], ['elec', 'Électricité uniquement']],
      household: 'Combien de personnes vivent chez vous ?',
      householdOpts: [['1', '1 personne'], ['2', '2 personnes'], ['3-4', '3–4 personnes'], ['5+', '5 ou plus']],
      usageToggle: 'Je connais ma consommation annuelle (facultatif)',
      usageHelp: 'Vous la trouvez sur votre facture de régularisation. Sinon, nous l’estimons provisoirement sur la base de votre ménage.',
      usageElec: 'Électricité (kWh par an)',
      usageGas: 'Gaz (kWh par an)',
      meter: 'Quel compteur avez-vous ?',
      meterOpts: [['digital', 'Compteur numérique'], ['analog', 'Compteur analogique'], ['unknown', 'Je ne sais pas']],
      meterHelp: 'Un compteur numérique a un petit écran et des boutons, et généralement un port P1.',
      solar: 'Avez-vous des panneaux solaires ?',
      solarOpts: [['yes', 'Oui'], ['no', 'Non'], ['unknown', 'Je ne sais pas']],
      extras: 'Avez-vous aussi… (facultatif)',
      extrasOpts: [['ev', 'Une voiture électrique'], ['hp', 'Une pompe à chaleur']],
      edge: 'Compteur à budget ou tarif social ? Contactez-nous d’abord, nous verrons ensemble ce qui est possible.',
      submit: 'Voir mon estimation',
      micro: 'Gratuit · sans engagement · vous choisissez après votre estimation',
    },
    est: {
      title: 'Votre économie indicative',
      tag: 'Indicatif',
      perYear: 'par an',
      for: (hh: string, place: string, energy: string) => `Pour ${hh} à ${place}, ${energy}.`,
      energyWord: { both: 'électricité et gaz', elec: 'électricité uniquement' } as Record<string, string>,
      hhWord: { '1': '1 personne', '2': '2 personnes', '3-4': 'un ménage de 3–4 personnes', '5+': 'un ménage de 5 personnes ou plus', usage: 'la consommation indiquée' } as Record<string, string>,
      after: (plan: string, price: string) => `Après votre abonnement (${plan}, ${price} par an)`,
      afterNote: 'Ce qu’il vous reste, selon cette estimation',
      recTitle: 'Recommandé pour vous',
      recPlus: "Switch Plus, avec garantie de gain. Si vous n'économisez pas plus que le prix de votre abonnement sur une année, vous récupérez 99 €.",
      recPremium: 'Premium. Vous avez un compteur numérique et des panneaux solaires : avec le June Dongle, vous voyez en direct votre autoconsommation et votre injection. Garantie de gain comprise.',
      solarNote: "Avec des panneaux solaires, votre économie dépend aussi de votre injection. Nous en tenons compte dans votre calcul personnel.",
      method: 'Comment calculons-nous cela ?',
      methodBody: 'Une fourchette indicative basée sur les économies moyennes de ménages au profil similaire [méthode, période et échantillon à confirmer par June]. Ce n’est ni une offre ni une promesse. Nous calculons votre économie personnelle après votre inscription, avec votre consommation réelle et votre contrat actuel.',
      cta: (plan: string) => `Continuer avec ${plan}`,
      edit: 'Modifier mes réponses',
      compare: 'Comparer les abonnements',
    },
    s2: {
      title: 'Choisissez votre abonnement et gardez votre estimation',
      plan: 'Votre abonnement',
      recBadge: 'Recommandé · avec garantie de gain',
      forYou: 'Adapté à votre situation',
      perYear: 'par an',
      perMonth: (m: string) => `${m} par mois, facturé annuellement`,
      planLines: { switch: 'Changement automatique, sans garantie', 'switch-plus': `Avec garantie de gain : ${eur(99, 'fr-be')} remboursés si vous n'économisez pas plus que le prix de votre abonnement`, premium: 'Avec June Dongle, données en direct et garantie de gain' } as Record<string, string>,
      premiumAnalog: 'Premium fonctionne uniquement avec un compteur numérique. Choisissez Switch ou Switch Plus, ou continuez si vous recevez bientôt un compteur numérique.',
      mode: 'Comment voulez-vous changer ?',
      modeOpts: [['auto', 'Automatiquement', 'June change pour vous dès que c’est plus avantageux. Vous êtes toujours informé.'], ['ask', "Demandez-moi d'abord", 'Vous validez vous-même chaque changement.']],
      green: "Je veux uniquement de l'électricité 100 % verte",
      greenHelp: 'Nous ne comparons alors que des contrats 100 % verts selon le fournisseur.',
      name: 'Prénom (facultatif)',
      email: 'Adresse e-mail',
      emailHelp: 'Nous vous envoyons votre estimation et le lien pour continuer. Nous l’utilisons uniquement pour votre inscription et votre compte.',
      terms: "J'accepte les [conditions générales] et j'ai lu la [déclaration de confidentialité].",
      marketing: 'Envoyez-moi de temps en temps des conseils et des nouvelles de June (facultatif).',
      code: 'Vous avez un code partenaire ou de parrainage ?',
      codeLabel: 'Code',
      submit: 'Démarrer mon inscription',
      micro: 'Vous ne payez rien pour l’instant. Vous disposez de 14 jours de rétractation après la souscription de votre abonnement.',
      next: 'Ensuite : votre adresse, votre code EAN et votre fournisseur actuel. Gardez votre facture à portée de main.',
      prev: 'Précédent',
    },
    done: {
      title: 'Consultez votre boîte mail',
      body: (e: string) => `Nous avons envoyé un e-mail à ${e}. Cliquez sur le lien pour finaliser votre inscription.`,
      summary: 'Vos choix',
      nextTitle: 'Et maintenant ?',
      next: ['Vous finalisez votre inscription via le lien : adresse, code EAN, fournisseur actuel.', 'Nous calculons votre économie personnelle avec votre consommation réelle.', 'Ensuite, June suit le marché pour vous, chaque mois.'],
      resend: "Rien reçu ? Vérifiez vos spams ou renvoyez l'e-mail.",
      home: "Retour à la page d'accueil",
      demo: "Prototype : rien n'a été envoyé.",
    },
    err: {
      pcEmpty: 'Indiquez votre code postal.',
      pcBad: 'Un code postal belge compte 4 chiffres, par ex. 1000.',
      choice: 'Faites un choix.',
      household: 'Choisissez le nombre de personnes, ou indiquez votre consommation annuelle.',
      usage: 'Cela nous semble beaucoup. Pouvez-vous vérifier ?',
      email: 'Cette adresse e-mail ne semble pas correcte.',
      emailEmpty: 'Indiquez votre adresse e-mail.',
      terms: 'Acceptez les conditions pour continuer.',
    },
    town: (pc: string, town: string, region: string, dso: string) => `${pc} ${town} · ${region} · gestionnaire de réseau ${dso}`,
    regionOnly: (pc: string, prov: string, region: string, dso: string) => `${pc} · ${prov}, ${region} · gestionnaire de réseau ${dso}`,
    regionVL: 'En Flandre, votre pic de puissance par quart d’heure compte aussi dans vos frais de réseau (tarif capacitaire). Cela ne change pas quand vous changez de fournisseur.',
    aside: {
      title: 'Pourquoi plus de 20 000 ménages ont choisi June',
      items: ["June n'est pas fournisseur : nous travaillons pour vous", "Votre électricité continue d'arriver, même compteur", "Pas d'indemnité de rupture chez votre fournisseur actuel", `Garantie de gain avec Switch Plus : ${eur(99, 'fr-be')} remboursés si vous n'économisez pas plus que le prix de votre abonnement`],
      privacy: 'Vos données restent chez June. Nous ne les vendons pas.',
    },
    customers: `plus de ${thousands(20000, 'fr-be')} clients`,
  },
};

/** Client data: province/region by postcode range + a few town names for confirmation (not exhaustive). */
export const postcodeData = {
  ranges: [
    [1000, 1299, 'BXL', 'Brussel', 'Bruxelles'], [1300, 1499, 'WA', 'Waals-Brabant', 'Brabant wallon'], [1500, 1999, 'VL', 'Vlaams-Brabant', 'Brabant flamand'],
    [2000, 2999, 'VL', 'Antwerpen', 'Anvers'], [3000, 3499, 'VL', 'Vlaams-Brabant', 'Brabant flamand'], [3500, 3999, 'VL', 'Limburg', 'Limbourg'],
    [4000, 4999, 'WA', 'Luik', 'Liège'], [5000, 5999, 'WA', 'Namen', 'Namur'], [6000, 6599, 'WA', 'Henegouwen', 'Hainaut'],
    [6600, 6999, 'WA', 'Luxemburg', 'Luxembourg'], [7000, 7999, 'WA', 'Henegouwen', 'Hainaut'], [8000, 8999, 'VL', 'West-Vlaanderen', 'Flandre-Occidentale'],
    [9000, 9999, 'VL', 'Oost-Vlaanderen', 'Flandre-Orientale'],
  ],
  regions: { VL: ['Vlaanderen', 'Flandre', 'Fluvius'], BXL: ['Brussel', 'Bruxelles', 'Sibelga'], WA: ['Wallonië', 'Wallonie', 'ORES of RESA|ORES ou RESA'] },
  towns: {
    1000: ['Brussel', 'Bruxelles'], 1030: ['Schaarbeek', 'Schaerbeek'], 1040: ['Etterbeek', 'Etterbeek'], 1050: ['Elsene', 'Ixelles'], 1060: ['Sint-Gillis', 'Saint-Gilles'],
    1070: ['Anderlecht', 'Anderlecht'], 1080: ['Sint-Jans-Molenbeek', 'Molenbeek-Saint-Jean'], 1090: ['Jette', 'Jette'], 1180: ['Ukkel', 'Uccle'], 1190: ['Vorst', 'Forest'],
    1200: ['Sint-Lambrechts-Woluwe', 'Woluwe-Saint-Lambert'], 1300: ['Waver', 'Wavre'], 1348: ['Louvain-la-Neuve', 'Louvain-la-Neuve'], 1400: ['Nijvel', 'Nivelles'],
    1410: ['Waterloo', 'Waterloo'], 1500: ['Halle', 'Hal'], 1800: ['Vilvoorde', 'Vilvorde'], 1930: ['Zaventem', 'Zaventem'], 2000: ['Antwerpen', 'Anvers'],
    2018: ['Antwerpen', 'Anvers'], 2100: ['Deurne', 'Deurne'], 2140: ['Borgerhout', 'Borgerhout'], 2300: ['Turnhout', 'Turnhout'], 2500: ['Lier', 'Lierre'],
    2800: ['Mechelen', 'Malines'], 2900: ['Schoten', 'Schoten'], 3000: ['Leuven', 'Louvain'], 3001: ['Heverlee', 'Heverlee'], 3300: ['Tienen', 'Tirlemont'],
    3500: ['Hasselt', 'Hasselt'], 3600: ['Genk', 'Genk'], 3700: ['Tongeren', 'Tongres'], 3800: ['Sint-Truiden', 'Saint-Trond'], 4000: ['Luik', 'Liège'],
    4020: ['Luik', 'Liège'], 4500: ['Hoei', 'Huy'], 4800: ['Verviers', 'Verviers'], 4700: ['Eupen', 'Eupen'], 5000: ['Namen', 'Namur'], 5100: ['Jambes', 'Jambes'],
    5500: ['Dinant', 'Dinant'], 6000: ['Charleroi', 'Charleroi'], 6700: ['Aarlen', 'Arlon'], 6900: ['Marche-en-Famenne', 'Marche-en-Famenne'], 7000: ['Bergen', 'Mons'],
    7100: ['La Louvière', 'La Louvière'], 7500: ['Doornik', 'Tournai'], 7700: ['Moeskroen', 'Mouscron'], 8000: ['Brugge', 'Bruges'], 8400: ['Oostende', 'Ostende'],
    8500: ['Kortrijk', 'Courtrai'], 8800: ['Roeselare', 'Roulers'], 8900: ['Ieper', 'Ypres'], 9000: ['Gent', 'Gand'], 9100: ['Sint-Niklaas', 'Saint-Nicolas'],
    9200: ['Dendermonde', 'Termonde'], 9300: ['Aalst', 'Alost'], 9400: ['Ninove', 'Ninove'], 9700: ['Oudenaarde', 'Audenarde'], 9800: ['Deinze', 'Deinze'],
  } as Record<number, [string, string]>,
};

/**
 * PLACEHOLDER estimate bands (€/year, gross, before the June fee). NOT June's model — claims register C17:
 * replace with June's server-side estimate before launch. Shown only as an indicative range with a method note.
 * Calibrated so the 3–4 person elec+gas band contains the published average (€ 326).
 */
export const estimateModel = {
  bands: {
    both: { '1': [150, 240], '2': [200, 300], '3-4': [250, 370], '5+': [300, 440] },
    elec: { '1': [70, 120], '2': [90, 150], '3-4': [120, 190], '5+': [150, 230] },
  } as Record<string, Record<string, [number, number]>>,
  perKwh: { elec: [0.035, 0.06], gas: [0.012, 0.02] },
  extras: { ev: 1.2, hp: 1.15 },
  prices: { switch: 69, 'switch-plus': 99, premium: 198 } as Record<string, number>,
  monthly: { switch: 5.75, 'switch-plus': 8.25, premium: 16.5 } as Record<string, number>,
};
